version: "3.6"

services:
  www_builder:
    container_name: urbo_www_builder
    command: npm run-script start
    restart: unless-stopped

  www:
    container_name: urbo_www_server
    restart: unless-stopped
